- block:
    - include_vars:
        file: roles/deploy.Consul/vars/key.yml
  rescue:
    - include_tasks: keygen.yml
    - include_tasks: config.yml

- name: Updating server config
  template:
    src: '{{ item.src }}.j2'
    dest: '{{ item.dest }}'
  with_items:
    - src: config.json
      dest: /etc/consul.d/config.json
    - src: consul.service
      dest: /etc/systemd/system/consul.service
  notify: Restart consul

- name: Updating services config
  template:
    src: '{{ item }}.json.j2'
    dest: '/etc/consul.d/{{ item }}.json'
  when: "item in group_names"
  with_items:
    - elasticsearch
    - logstash
    - kibana
    - redis
  notify: Restart consul
