- block:
    - include_vars:
        file: roles/deploy.Consul/vars/key.yml
  rescue:
    - include_tasks: keygen.yml
    - include_tasks: config.yml

- name: Updating server config
  template:
    src: 'consul/{{ item.src }}.j2'
    dest: '{{ item.dest }}'
  with_items:
    - src: config.json
      dest: /etc/consul.d/config.json
    - src: consul.service
      dest: /etc/systemd/system/consul.service
    - src: consul-dns.service
      dest: /etc/systemd/system/consul-dns.service
  notify: Restart consul

- name: Updating services config
  template:
    src: 'consul/service_{{ item }}.json.j2'
    dest: '/etc/consul.d/{{ item }}.json'
  when: "item in group_names"
  with_items:
    - elasticsearch
    - logstash
    - kibana
    - redis
  notify: Reload consul
  register: templates

- name: Listing current config files
  shell: "ls *.json | grep -v config"
  args:
    chdir: /etc/consul.d/
  ignore_errors: True
  changed_when: false
  register: allTemplates

# - debug:
#     msg: "{{ templates.results|selectattr('item', 'string')|map(attribute='item')|list }}"
#
# - debug:
#     msg: "{{ allTemplates.stdout_lines }}"
#
# - name: Removing unmanaged config files
#   file:
#     path: "/etc/consul.d/{{ item }}"
#     state: absent
#   when: "item not in templates.results|selectattr('item', 'string')|map(attribute='item')|list "
#   with_items: "{{ allTemplates.stdout_lines }}"

- block:
    - name: Checking local port 53
      wait_for:
        port: 53
        timeout: 3
  rescue:
    - name: Enable DNS port forwarding
      command: '{{ item }}'
      changed_when: false
      with_items:
        - iptables -t nat -A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
        - iptables -t nat -A PREROUTING -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
        - iptables -t nat -A OUTPUT -d localhost -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
        - iptables -t nat -A OUTPUT -d localhost -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
