- block:
    - include_vars:
        file: roles/deploy.Consul/vars/key.yml
  rescue:
    - include_tasks: keygen.yml
    - include_tasks: config.yml

- name: Updating server config
  template:
    src: '{{ item.src }}.j2'
    dest: '{{ item.dest }}'
  with_items:
    - src: config.json
      dest: /etc/consul.d/config.json
    - src: consul.service
      dest: /etc/systemd/system/consul.service
  notify: Restart consul

- name: Updating services config
  template:
    src: '{{ item }}.j2'
    dest: '/etc/consul.d/{{ item }}'
  when: "item in group_names"
  with_items:
    - elasticsearch.json
    - logstash.json
    - kibana.json
    - redis.json
  notify: Restart consul
  register: templates

- name: Listing current config files
  shell: "ls /etc/consul.d/*.json | grep -v config"
  ignore_errors: yes
  changed_when: false
  register: allTemplates

- name: Removing unmanaged config files
  file:
    path: "/etc/consul.d/{{ item }}"
    state: absent
  with_items: "{{ allTemplates.stdout_lines }}"
  when: "item not in (templates.results|selectattr('item', 'string')|map(attribute='item')|list)"

- block:
    - name: Checking local port 53
      wait_for:
        port: 53
        timeout: 3
  rescue:
    - name: Enable DNS port forwarding
      command: '{{ item }}'
      changed_when: false
      with_items:
        - iptables -t nat -A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
        - iptables -t nat -A PREROUTING -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
        - iptables -t nat -A OUTPUT -d localhost -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
        - iptables -t nat -A OUTPUT -d localhost -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
