- block:
    - name: Uploading command file
      copy:
        src: "downloaded_files/consul-{{ consul_version }}"
        dest: /usr/local/bin/consul
        mode: 0755
      notify: Restart consul
  rescue:
    - include_tasks: download.yml
    - include_tasks: install.yml
  always:
    - name: Creating user 'consul'
      user:
        name: consul
    - name: Creating /etc/consul.d/chk_scripts
      file:
        path: /etc/consul.d/chk_scripts
        state: directory
        owner: consul
        group: consul
    - name: Creating /var/consul
      file:
        path: /var/consul
        state: directory
        owner: consul
        group: consul
