- name: Config /usr/lib/systemd/system/elasticsearch.service
  ini_file:
    path: /usr/lib/systemd/system/elasticsearch.service
    section: Service
    option: LimitMEMLOCK
    value: infinity

- name: Installing enable-thp.service
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items:
    - src: enable-transparent-hugepages
      dest: /usr/bin/enable-transparent-hugepages
      mode: 554
    - src: enable-thp.service
      dest: /etc/systemd/system/enable-thp.service
  notify: Start enable-thp.service

- name: Updating ElasticSearch configuration
  template:
    src: '{{ item }}.j2'
    dest: '/etc/elasticsearch/{{ item }}'
  with_items:
    - jvm.options
    - elasticsearch.yml

- include_tasks: "plugins.yml target={{ target }}"
  with_items: "{{ elastic_plugins }}"
  loop_control:
    loop_var: target
  when: node_ingest is defined and node_ingest == true

- name: Installing logrotate configure
  template:
    src: logrotate_elasticsearch.j2
    dest: /etc/logrotate.d/elasticsearch

- name: Starting ElasticSearch service
  service:
    name: elasticsearch
    daemon_reload: yes
    enabled: yes
    state: started

- name: Waiting for service started
  wait_for:
    host: "{{ bind_address }}"
    port: '9200'
    timeout: 120

- name: Setup index default settings
  uri:
    url: http://ingest.elastic.service.{{ consul_dc_name }}.consul:{{ elastic_http_port }}/_template/active-logs
    method: PUT
    body: "{{ lookup('file', 'indices_default_settings.json') }}"
    body_format: json
  when: inventory_hostname == groups['kibana'][0]
