- name: Config /etc/systemd/system/elasticsearch.service.d/override.conf
  ini_file:
    path: /etc/systemd/system/elasticsearch.service.d/override.conf
    section: Service
    option: LimitMEMLOCK
    value: infinity

- name: Installing enable-thp.service
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items:
    - src: enable-transparent-hugepages
      dest: /usr/bin/enable-transparent-hugepages
      mode: 554
    - src: enable-thp.service
      dest: /etc/systemd/system/enable-thp.service
  notify: Start enable-thp.service

- name: Updating ElasticSearch configuration
  template:
    src: '{{ item }}.j2'
    dest: '/etc/elasticsearch/{{ item }}'
  with_items:
    - jvm.options
    - elasticsearch.yml

- include_tasks: "plugins.yml target={{ target }}"
  with_items: "{{ elastic_plugins }}"
  loop_control:
    loop_var: target
  when: "'ingest' in elastic_instance_roles"

- name: Installing logrotate configure
  template:
    src: logrotate_elasticsearch.j2
    dest: /etc/logrotate.d/elasticsearch

- name: Starting ElasticSearch service
  service:
    name: elasticsearch
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: Waiting for service started
  wait_for:
    host: "{{ bind_address }}"
    port: "{{ item }}"
    timeout: 120
  with_items:
    - 9300
    - 9200
