- name: Config /etc/systemd/system/elasticsearch.service.d/override.conf
  ini_file:
    path: /etc/systemd/system/elasticsearch.service.d/override.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: Service
      option: LimitMEMLOCK
      value: infinity

- name: Enable transparent hugepages
  copy:
    src: enable-transparent-hugepages
    dest: /etc/init.d/enable-thp
    mode: 554
  notify: Start enable-thp

- name: Updating ElasticSearch configuration
  vars:
    searchguard_enabled: false
  template:
    src: 'elasticsearch/{{ item }}.j2'
    dest: '/etc/elasticsearch/{{ item }}'
  with_items:
    - jvm.options
    - elasticsearch.yml

- name: Installing logrotate configure
  template:
    src: elasticsearch/logrotate_elasticsearch.j2
    dest: /etc/logrotate.d/elasticsearch

- name: Starting ElasticSearch service
  service:
    name: elasticsearch
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Waiting for service started
  wait_for:
    host: "{{ bind_address }}"
    port: "{{ item }}"
    timeout: 60
  with_items:
    - 9300
    - 9200
