- name: config /usr/lib/systemd/system/elasticsearch.service
  ini_file:
    path: /usr/lib/systemd/system/elasticsearch.service
    section: Service
    option: LimitMEMLOCK
    value: infinity

- name: updating ElasticSearch configuration
  template:
    src: '{{ item }}.j2'
    dest: '/etc/elasticsearch/{{ item }}'
  with_items:
    - jvm.options
    - elasticsearch.yml

- include_tasks: "plugins.yml target={{ target }}"
  with_items: "{{ elastic_plugins }}"
  loop_control:
    loop_var: target
  when: node_ingest is defined and node_ingest == true

- name: starting ElasticSearch service
  service:
    name: elasticsearch
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: waiting for service started
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_' + bond_interface]['ipv4']['address'] }}"
    port: '9200'
    timeout: 120

- name: setup index default settings
  uri:
    url: http://elastic-ingest.service.{{ consul_dc_name }}.consul:{{ elastic_http_port }}/_template/active-logs
    method: PUT
    body: "{{ lookup('file', 'indices_default_settings.json') }}"
    body_format: json
  when: inventory_hostname == groups['kibana'][0]
