- name: Checking if the node has been back to cluster or not.
  uri:
    url: "http://{{ bind_address }}:{{ elastic_http_port }}/_cat/nodes"
    return_content: yes
  register: nodesSt
  until: "(ansible_hostname in nodesSt.content) or (hostvars[inventory_hostname]['ansible_host'] in nodesSt.content)"
  retries: 300
  delay: 10

- name: Enable shard allocation.
  uri:
    url: "http://{{ bind_address }}:{{ elastic_http_port }}/_cluster/settings"
    method: PUT
    body: "{{ lookup('file','enable_shard.json') }}"
    body_format: json

- name: Waiting for the cluster turn to green.
  uri:
    url: "http://{{ bind_address }}:{{ elastic_http_port }}/_cat/health"
    return_content: yes
  register: healthSt
  until: "'green' in healthSt.content"
  retries: 300
  delay: 10
