- name: checking cluster health status
  uri:
    url: http://{{ bind_address }}:{{ elastic_http_port }}/_cluster/health
    method: GET
    return_content: yes
    body_format: json
  register: health

- fail:
    msg: "Current cluster status is not 'green', please fix it before upgrade."
  when: health.json.status != "green"

- name: stopping shards
  uri:
    url: "http://{{ bind_address }}:{{ elastic_http_port }}/_cluster/settings"
    method: PUT
    body: "{{ lookup('file','disable_shard.json') }}"
    body_format: json
  when: node_data is sameas true

- name: stopping service
  service:
    name: elasticsearch
    state: stopped

- name: waiting for port down
  wait_for:
    host: "{{ bind_address }}"
    port: '{{ elastic_http_port }}'
    state: stopped

- name: removing plugins
  elasticsearch_plugin:
    name: "{{ item }}"
    state: absent
  ignore_errors: yes
  with_items: "{{ elastic_plugins }}"
