- block:

    - name: 'Uploading elasticsearch-{{ elk_version }}.rpm'
      copy:
        src: 'downloaded_files/elk-{{ elk_version }}/elasticsearch-{{ elk_version }}.rpm'
        dest: /tmp/

    - name: 'Installing elasticsearch-{{ elk_version }}.rpm'
      yum:
        name: '/tmp/elasticsearch-{{ elk_version }}.rpm'
        state: present

    - include_tasks: plugins.yml
      loop: "{{ elastic_plugins }}"
      loop_control:
        loop_var: target
      when: elk_version is version('6.7.0', operator='lt', strict=True)

    - name: Starting elasticsearch service
      service:
        name: elasticsearch
        state: restarted
        daemon_reload: yes

  rescue:

    - include_tasks: download.yml
      vars:
        format: rpm
    - include_tasks: '{{ ansible_os_family }}.yml'
    - meta: clear_host_errors

  always:

    - name: 'Removing /tmp/elasticsearch-{{ elk_version }}.rpm'
      file:
        path: '/tmp/elasticsearch-{{ elk_version }}.rpm'
        state: absent
