- name: Reload haproxy service
  service:
    name: haproxy
    state: reloaded
    enabled: yes
    daemon_reload: yes
  listen: Reload haproxy

- name: Wating for ports connected
  wait_for:
    host: "{{ bind_address }}"
    port: "{{ item.front_port }}"
    timeout: 30
  when: item.expose|bool == true
  with_items: "{{ haproxy_backends }}"
  listen: Reload haproxy
