- hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
    - vars/download_urls.yml
  vars_prompt:
    - name: "format"
      prompt: "What type of files do you need?[rpm|deb]"
      default: "rpm"
      private: no
  pre_tasks:
    - name: Checking group_vars/all.yml
      stat:
        path: group_vars/all.yml
      delegate_to: localhost
      run_once: yes
      become: no
      register: result
    - fail:
        msg: |
          Please create group_vars/all.yml from group_vars/all.yml.example,
          and edit it to suit your environment before your deploy.
      when: result.stat.exists == false
      delegate_to: localhost
      run_once: yes
      become: no
    - name: Create local downloaded_files directory
      file:
        path: downloaded_files
        state: directory
  tasks:
    - include_role: name=deploy.ElasticSearch tasks_from=download
      tags: elasticsearch
    - include_role: name=deploy.Kibana tasks_from=download
      tags: kibana
    - include_role: name=deploy.Logstash tasks_from=download
      tags: logstash
    - include_role: name=deploy.Monit tasks_from=download
      tags: monit
    - include_role: name=deploy.Consul tasks_from=download
      tags: consul
    - include_role: name=deploy.Beats tasks_from=download
      with_items:
        - filebeat
        - metricbeat
        - packetbeat
      loop_control:
        loop_var: target
      tags: beats
    - include_role: name=deploy.Redis tasks_from=download
      tags: redis
    - include_role: name=deploy.Haproxy tasks_from=download
      tags: haproxy
