- hosts: all
  become: yes
  serial: 33%
  gather_facts: no
  tasks:
    - name: "Checking {{ inventory_dir }}/group_vars/all.yml"
      stat:
        path: "{{ inventory_dir }}/group_vars/all.yml"
      delegate_to: localhost
      run_once: yes
      become: no
      register: result
    - fail:
        msg: "Please create {{ inventory_dir }}/group_vars/all.yml from inventories/example/group_vars/all.yml, and edit it to suit your environment before your deploy."
      when: result.stat.exists == false
      delegate_to: localhost
      run_once: yes
      become: no
    - include_role:
        name: init
        tasks_from: check_python.yml

- hosts: all
  become: yes
  serial: 33%
  vars_files:
    - vars/download_urls.yml
    - vars/sysctl_rules.yml
  roles:
    - init
    - deploy.Chrony
