- hosts: all
  become: yes
  serial:
    - 1
    - 33%
  roles:
    - deploy.Consul
  post_tasks:
    - block:
        - name: Waiting for service consul started
          wait_for:
            host: "{{ bind_address }}"
            port: 8600
            timeout: 30
      rescue:
        - service:
            name: consul
            state: restarted
        - wait_for:
            host: "{{ bind_address }}"
            port: 8600
            timeout: 30
