- hosts: kibana
  become: yes
  serial:
    - 1
    - 33%
  roles:
    - deploy.Kibana
    - deploy.ElasticSearch
    - deploy.Curator
  post_tasks:
    - block:
        - name: Waiting for service started
          wait_for:
            port: '{{ kibana_port }}'
            timeout: 120
      rescue:
        - service:
            name: kibana
            state: restarted
            enabled: yes
        - wait_for:
            port: '{{ kibana_port }}'
            timeout: 120
