- hosts: kibana
  become: yes
  serial:
    - 1
    - 30%
  roles:
    - deploy.Consul
    - deploy.Kibana
    - deploy.ElasticSearch
    - deploy.Curator
    - deploy.Monit
  post_tasks:
    - block:
        - name: waiting for service started
          wait_for:
            port: '{{ kibana_port }}'
            timeout: 120
      rescue:
        - service:
            name: kibana
            state: restarted
            enabled: yes
        - wait_for:
            port: '{{ kibana_port }}'
            timeout: 120
