- hosts: logstash
  become: yes
  serial:
    - 1
    - 10%
  roles:
    - deploy.Logstash
  post_tasks:
    - block:
        - name: Waiting for service started
          wait_for:
            port: 9600
            timeout: 120
      rescue:
        - name: Set /var/lib/logstash ownership
          file:
            path: '{{ item }}'
            state: directory
            owner: logstash
            group: logstash
            recurse: yes
          with_items:
            - '{{ logstash_log_path }}'
            - '{{ logstash_data_path }}'
        - service:
            name: logstash
            state: restarted
        - wait_for:
            port: 9600
            timeout: 120
