- hosts: kibana
  become: yes
  serial:
    - 1
    - 33%
  vars_files:
    - vars/curator.yml
    - vars/search_guard.yml
    - vars/search_guard_auth.yml
  roles:
    - name: deploy.Kibana
    - name: deploy.Curator
      when: inventory_hostname == groups['kibana'][0]
  post_tasks:
    - block:
        - name: Waiting for service started
          wait_for:
            host: "{{ bind_address }}"
            port: "{{ kibana_port }}"
            timeout: 180
      rescue:
        - service:
            name: kibana
            state: restarted
            enabled: yes
        - wait_for:
            host: "{{ bind_address }}"
            port: "{{ kibana_port }}"
            timeout: 120
