- hosts: logstash
  become: yes
  vars_files:
    - vars/logstash.yml
  serial:
    - 1
    - 33%
  roles:
    - deploy.Logstash
  post_tasks:
    - include_role:
        name: deploy.Logstash
        tasks_from: report.yml
