- hosts: all
  become: yes
  # serial:
  #   - 1
  #   - 33%
  roles:
    - deploy.Monit
  post_tasks:
    - block:
        - name: Waiting for service started
          wait_for:
            port: 2812
            timeout: 35
      rescue:
        - service:
            name: monit
            state: restarted
        - wait_for:
            port: 2812
            timeout: 120
