- hosts: all
  become: yes
  serial: 33%
  vars_files:
    - vars/search_guard.yml
    - vars/search_guard_auth.yml
  roles:
    - {
      role: deploy.Beats,
      target: filebeat,
      tags: filebeat
    }

- hosts: all
  become: yes
  serial: 33%
  vars_files:
    - vars/search_guard.yml
    - vars/search_guard_auth.yml
  roles:
    - {
      role: deploy.Beats,
      target: metricbeat,
      tags: metricbeat
    }

- hosts: all
  become: yes
  serial: 33%
  vars_files:
    - vars/search_guard.yml
    - vars/search_guard_auth.yml
  roles:
    - {
      role: deploy.Beats,
      target: packetbeat,
      tags: packetbeat
    }
