- hosts: all
  become: yes
  serial:
    - 1
  tasks:
    - apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == 'Debian'
    - yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'
