- hosts: all
  become: yes
  serial: 1
  vars_files:
    - vars/curator.yml
  tasks:
    - name: Restart kibana service
      systemd:
        name: kibana
        state: restarted
        enabled: yes
