# WARNING: This playbook is for testing only! Do NOT use it in production environment!
- hosts: all
  gather_facts: no
  tasks:
    - group_by:
        key: chaos
      when: groups['all'] | random == inventory_hostname

- hosts: chaos
  gather_facts: no
  become: yes
  tasks:
    - command: reboot
