- name: Start disable-thp.service
  service:
    name: disable-thp
    state: started
    daemon_reload: yes
    enabled: yes
  listen: Restart redis-server

- name: Restart redis-server service
  service:
    name: redis-server
    state: restarted
    daemon_reload: yes
    enabled: yes
  listen: Restart redis-server

- name: Waiting for redis-server started
  wait_for:
    host: "{{ bind_address }}"
    port: 6379
  listen: Restart redis-server

- name: Restart redis-sentinel service
  service:
    name: redis-sentinel
    state: restarted
    daemon_reload: yes
    enabled: yes
  listen: Restart redis-sentinel

- name: Waiting for redis-sentinel started
  wait_for:
    host: "{{ bind_address }}"
    port: 26379
  listen: Restart redis-sentinel
