- name: Start disable-thp.service
  service:
    name: disable-thp
    state: started
    daemon_reload: yes
    enabled: yes

- name: Restart redis-server
  service:
    name: redis-server
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Restart redis-sentinel
  service:
    name: redis-sentinel
    state: restarted
    daemon_reload: yes
    enabled: yes
