- name: Updating redis.conf
  template:
    src: "redis.conf.j2"
    dest: "/etc/redis/redis.conf"
    owner: redis
    group: root
    mode: 0660
  notify: Restart redis-server

- name: Updating sentinel.conf
  lineinfile:
    path: /etc/redis/sentinel.conf
    create: yes
    owner: redis
    group: root
    mode: 0660
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  with_items:
    - line: "bind {{ bind_address }}"
      regexp: "^bind"
    - line: "port 26379"
      regexp: "^port"
    - line: "sentinel monitor elk-redis {{ sentinel_redis_master | default(groups['redis'][0]) }} 6379 2"
      regexp: "^sentinel monitor"
    - line: "sentinel down-after-milliseconds elk-redis 5000"
      regexp: "^sentinel down-after-milliseconds"
    - line: "sentinel parallel-syncs elk-redis 1"
      regexp: "^sentinel parallel-syncs"
    - line: "sentinel failover-timeout elk-redis 30000"
      regexp: "^sentinel failover-timeout"
  notify: Restart redis-sentinel
