- name: Setup /etc/security/limits.conf
  blockinfile:
    path: /etc/security/limits.conf
    block: |
      redis soft nofile 10240
      redis hard nofile 10240

- name: Coping 'Disable Transparent Hugepages' script
  copy:
    src: disable-transparent-hugepages
    dest: /usr/bin/disable-transparent-hugepages
    mode: 0755

- name: Create 'Disable Transparent Hugepages' service
  copy:
    src: disable-thp.service
    dest: /lib/systemd/system/
    owner: root
    group: root
    mode: 0544
  notify: Start disable-thp.service

- meta: flush_handlers
