- name: Validate config
  command: /usr/local/bin/consul validate -quiet /etc/consul.d/
  listen:
    - Restart consul
    - Reload consul

- name: Restart consul service
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  with_items:
    - consul-dns
    - consul
  listen: Restart consul

- name: Restart resolvconf service
  service:
    name: resolvconf
    state: restarted
  when: ansible_os_family == 'Debian'

- name: Reload consul
  service:
    name: consul
    state: reloaded
