- name: Test monit config
  command: /usr/local/bin/monit -t
  listen: "Reload monit"

- name: Enable monit service
  service:
    name: monit
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Reload monit service
  service:
    name: monit
    state: reloaded
  listen: "Reload monit"
