- name: update monitrc
  template:
    src: monitrc.j2
    dest: /etc/monitrc
    mode: 0700
    owner: root
    group: root
  notify: "reload monit"

- name: install/update config for all
  template:
    src: '{{ item }}.j2'
    dest: '/etc/monit.d/{{ item }}'
    mode: 0700
  with_items:
    - check_fs_usage
    - check_sysload
    - check_services
  notify: "reload monit"

- name: install/update config on elastic master nodes
  template:
    src: '{{ item }}.j2'
    dest: '/etc/monit.d/{{ item }}'
    mode: 0600
  when: "'elasticMasterNode' in group_names"
  with_items:
    - check_hosts
  notify: "reload monit"
