- name: Update monitrc
  template:
    src: monitrc.j2
    dest: /etc/monitrc
    mode: 0600
    owner: root
    group: root
  notify: "Reload monit"

- name: Install/update config for all
  template:
    src: '{{ item }}.j2'
    dest: '/etc/monit.d/{{ item }}'
    mode: 0600
  with_items:
    - check_fs_usage
    - check_sysload
    - check_services
  notify: "Reload monit"
  register: templatesAll

- name: Install/update config on elastic master nodes
  template:
    src: '{{ item }}.j2'
    dest: '/etc/monit.d/{{ item }}'
    mode: 0600
  when: "'esMasters' in group_names"
  with_items:
    - check_hosts
  notify: "Reload monit"
  register: templatesMaster

- name: Listing current config files
  command: "ls /etc/monit.d/"
  ignore_errors: yes
  changed_when: false
  register: templatesList

- name: Removing unmanaged config files
  file:
    path: "/etc/monit.d/{{ item }}"
    state: absent
  with_items: "{{ templatesList.stdout_lines }}"
  when: "item not in (templatesAll.results|selectattr('item', 'string')|map(attribute='item')|list + templatesMaster.results|selectattr('item', 'string')|map(attribute='item')|list)"
