- block:
    - name: Get monit summary
      command: /usr/local/bin/monit summary
      register: summary
    - name: Create report file under install_report/monit
      lineinfile:
        path: "install_report/monit/{{ inventory_hostname }}.txt"
        regexp: "^{{ item | truncate(20, True) }}"
        line: "{{ item }}"
        create: yes
      changed_when: false
      with_items: "{{ summary.stdout_lines }}"
      delegate_to: localhost
      become: no
  rescue:
    - name: "Create local directory install_report/monit"
      file:
        path: "install_report/monit"
        state: directory
      delegate_to: localhost
      become: no
    - include_tasks: report.yml
