- block:
    - name: Get monit summary
      command: /usr/local/bin/monit summary
      changed_when: false
      register: summary
    - name: Create report file under install_report/monit
      lineinfile:
        path: "install_report/monit/{{ inventory_hostname }}.txt"
        regexp: "^{{ item | truncate(20, True) }}"
        line: "{{ item }}"
        create: yes
      changed_when: false
      with_items: "{{ summary.stdout_lines | sort }}"
      delegate_to: localhost
      become: no
    - name: "Fetching /etc/monitrc to local 'install_report' directory"
      fetch:
        src: "/etc/monitrc"
        dest: "install_report"
        fail_on_missing: false
  rescue:
    - name: "Create local directory install_report/monit"
      file:
        path: "install_report/monit"
        state: directory
      delegate_to: localhost
      become: no
    - include_tasks: report.yml
