- name: Restarting elasticsearch service
  service:
    name: elasticsearch
    state: restarted
    enabled: yes
    daemon_reload: yes
  listen: Restarting elasticsearch

- wait_for:
    host: "{{ bind_address }}"
    port: '{{ item }}'
  with_items:
    - 9300
    - 9200
  listen: Restarting elasticsearch

- name: Updating Search Guard index
  command: "bash sgadmin.sh -cd ../sgconfig/ -cert elk-client.pem -key elk-client.key -cacert /etc/elasticsearch/tls/elk-ca.pem -nhnv {{ item }}"
  with_items:
    - '--accept-red-cluster -icl'
    - '-rl -icl'
  args:
    chdir: /usr/share/elasticsearch/plugins/search-guard-{{ sg_es_ver.split('.') | first }}/tools
  changed_when: false
  register: init
  until: init is succeeded
  retries: 10
  delay: 10

- name:  Start enable-thp
  sysvinit:
    name: enable-thp
    state: started
    enabled: yes
