- name: Start enable-thp.service
  service:
    name: enable-thp
    state: started
    enabled: yes
    daemon_reload: yes
  listen: Restarting elasticsearch

- name: Restarting elasticsearch service
  service:
    name: elasticsearch
    state: restarted
    enabled: yes
    daemon_reload: yes
  listen: Restarting elasticsearch

- wait_for:
    host: "{{ bind_address }}"
    port: '{{ item }}'
  with_items:
    - 9300
    - 9200
  listen: Restarting elasticsearch
