- name: Restart kibana service
  service:
    name: kibana
    state: restarted
    enabled: yes
    daemon_reload: yes
  listen: Restart kibana

- name: Waiting for kibana started
  wait_for:
    host: "{{ bind_address }}"
    port: "{{ kibana_port }}"
    timeout: 180
  register: status
  retries: 3
  until: status is succeeded
  listen: Restart kibana
