- name: Restart kibana service
  service:
    name: kibana
    state: restarted
    enabled: yes
    daemon_reload: yes
  listen: Restart kibana

- name: Waiting for kibana started
  wait_for:
    host: "{{ bind_address }}"
    port: "{{ kibana_port }}"
    timeout: 120
  listen: Restart kibana
