- block:
    - name: "Create {{ ansible_user_dir }}/.curator"
      file:
        path: "{{ ansible_user_dir }}/.curator"
        state: directory
    - name: "Updating action file {{ target }}.yml"
      template:
        src: 'curator/{{ target }}.yml.j2'
        dest: '{{ ansible_user_dir }}/.curator/{{ target }}.yml'
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        validate: "/usr/local/bin/curator --dry-run %s"
  rescue:
    - name: "Create directory {{ ansible_user_dir }}/.curator/"
      file:
        path: "{{ ansible_user_dir }}/.curator/"
        state: directory
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
    - name: Create curator.yml
      template:
        src: 'curator/curator.yml.j2'
        dest: '{{ ansible_user_dir }}/.curator/curator.yml'
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
    - include_tasks: action_files.yml
