- block:
    - name: Checking command 'curator'
      command: /usr/local/bin/curator --version
      changed_when: false
  rescue:
    - include_tasks: 'install.yml target={{ item }}'
      with_items:
        - setuptools-38.5.2
        - certifi-2018.1.18
        - click-6.7
        - PyYAML-3.12
        - voluptuous-0.11.1
        - urllib3-1.22
        - elasticsearch-6.1.1
        - elasticsearch-curator-5.4.1
    - name: Create soft link | RedHat
      file:
        src: /usr/bin/curator
        path: /usr/local/bin/curator
        state: link
      when: ansible_os_family == 'RedHat'
      
- block:
    - include_tasks: 'action_files.yml target={{ item }}'
      with_items:
        - hot_to_warm
    - include_tasks: 'cron.yml target={{ item }}'
      with_items:
        - hot_to_warm
  when: "(groups['elasticWarmNode']|length) > 0"
