- block:
    - name: Checking command 'curator'
      command: /usr/local/bin/curator --version
      changed_when: false
  rescue:
    - include_tasks: 'install.yml'
      loop: "{{ pip_pkgs }}"
      loop_control:
        loop_var: target
    - name: Create soft link | RedHat
      file:
        src: /usr/bin/curator
        path: /usr/local/bin/curator
        state: link
      when: ansible_os_family == 'RedHat'

- block:
    - include_tasks: action_files.yml
      loop:
        - hot_to_warm
      loop_control:
        loop_var: target
    - include_tasks: cron.yml
      loop:
        - hot_to_warm
      loop_control:
        loop_var: target
  when: "( groups['esWarms'] | count ) > 0"
