- name: Checking '/usr/share/elasticsearch/plugins/search-guard-6/search-guard-6-{{ sg_es_ver }}.jar'
  stat:
    path: "/usr/share/elasticsearch/plugins/search-guard-6/search-guard-6-{{ sg_es_ver }}.jar"
  register: sg_es

- block:
    - include_tasks: tlstool.yml
  when: inventory_hostname == ansible_play_hosts[0]

# - block:
#     - name: Disable elasticsearch shard allocation | http
#       uri:
#         url: http://elastic.service.{{ consul_dc_name }}.consul:9200/_cluster/settings?pretty
#         method: PUT
#         body_format: json
#         body: |
#           {
#             "persistent": {
#               "cluster.routing.allocation.enable": "none"
#             }
#           }
#   rescue:
#     - name: Disable elasticsearch shard allocation | https
#       uri:
#         url: https://elastic.service.{{ consul_dc_name }}.consul:9200/_cluster/settings?pretty
#         method: PUT
#         body_format: json
#         body: |
#           {
#             "persistent": {
#               "cluster.routing.allocation.enable": "none"
#             }
#           }
#       ignore_errors: true
#   when:
#     - inventory_hostname == ansible_play_hosts[0]
#     - sg_es.stat.exists == false

- block:
    - name: Stopping elasticsearch nodes
      service:
        name: elasticsearch
        state: stopped
    - name: Waiting for elasticsearch stopped
      wait_for:
        host: "{{ bind_address }}"
        port: "{{ elastic_http_port }}"
        state: stopped
    - name: Uploading search guard files
      copy:
        src: "downloaded_files/searchguard/search-guard-6-{{ sg_es_ver }}.zip"
        dest: "/tmp/search-guard-6-{{ sg_es_ver }}.zip"
    - name: Installing search guard
      command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install -b file:///tmp/search-guard-6-{{ sg_es_ver }}.zip"
      changed_when: false
  when: sg_es.stat.exists == false

- block:
    - name: Creating '/etc/elasticsearch/tls' directory
      file:
        path: /etc/elasticsearch/tls
        state: directory
    - name: Uploading tls files to /etc/elasticsearch/tls
      copy:
        src: "downloaded_files/searchguard/out/{{ item }}"
        dest: /etc/elasticsearch/tls
        mode: 0400
        owner: elasticsearch
        group: elasticsearch
      with_items:
        - "{{ tls_file_name }}.key"
        - "{{ tls_file_name }}.pem"
        - esnode.key
        - esnode.pem
    - name: Initial search guard index
      command: bash sgadmin.sh -cd ../sgconfig/ \
        -cert /root/sg_tlstool/out/haibin.pem \
        -key /root/sg_tlstool/out/haibin.key \
        -cacert /etc/elasticsearch/tls/elk-ca.pem \
        -nhnv --accept-red-cluster -icl
      args:
        chdir: /usr/share/elasticsearch/plugins/search-guard-6/tools
      when: inventory_hostname == ansible_play_hosts[0]
    # - name: Add config block into /etc/elasticsearch/elasticsearch.yml
    #   blockinfile:
    #     path: /etc/elasticsearch/elasticsearch.yml
    #     block: "{{ sg_es_config }}"
    #     marker: "# {mark} ANSIBLE MANAGED BLOCK FOR SEARCH GUARD"
    #   notify: Restart elasticsearch
