- include_tasks: download.yml
  vars:
    format: deb

- name: "Uploading {{ target }}-{{ elk_version }}-amd64.deb"
  copy:
    src: "downloaded_files/elk-{{ elk_version }}/{{ target }}-{{ elk_version }}-amd64.deb"
    dest: "/tmp/{{ target }}-{{ elk_version }}-amd64.deb"

- block:
    - name: 'Installing {{ target }}-{{ elk_version }}-amd64.deb'
      apt:
        deb: '/tmp/{{ target }}-{{ elk_version }}-amd64.deb'
    - name: 'Restarting {{ target }} service'
      service:
        name: '{{ target }}'
        state: restarted
        enabled: yes
  rescue:
    - command: "dpkg -i /tmp/{{ target }}-{{ elk_version }}-amd64.deb"

- name: "Removing /tmp/{{ target }}-{{ elk_version }}-amd64.deb"
  file:
    path: "/tmp/{{ target }}-{{ elk_version }}-amd64.deb"
    state: absent
