- block:
    - stat:
        path: "downloaded_files/{{ target }}-{{ elk_version }}-amd64.deb"
      register: result
      failed_when: result.stat.exists == false
      when: format == 'deb'
      delegate_to: localhost
      become: no
      run_once: true
  rescue:
    - name: "Downloading https://artifacts.elastic.co/downloads/beats/{{ target }}/{{ target }}-{{ elk_version }}-amd64.deb"
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/{{ target }}/{{ target }}-{{ elk_version }}-amd64.deb"
        dest: "downloaded_files/"
      register: download
      until: download is succeeded
      retries: 5
      delay: 10
      delegate_to: localhost
      become: no
      run_once: true

- block:
    - stat:
        path: "downloaded_files/{{ target }}-{{ elk_version }}-x86_64.rpm"
      register: result
      failed_when: result.stat.exists == false
      when: format == 'rpm'
      delegate_to: localhost
      become: no
      run_once: true
  rescue:
    - name: "Downloading https://artifacts.elastic.co/downloads/beats/{{ target }}/{{ target }}-{{ elk_version }}-x86_64.rpm"
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/{{ target }}/{{ target }}-{{ elk_version }}-x86_64.rpm"
        dest: "downloaded_files/"
      register: download
      until: download is succeeded
      retries: 5
      delay: 10
      delegate_to: localhost
      become: no
      run_once: true
