- name: Updating filebeat.yml
  template:
    src: "filebeat.yml.j2"
    dest: "/etc/filebeat/filebeat.yml"
    mode: 0600
  notify: Restart filebeat

- name: Enable filebeat modules
  command: "filebeat modules enable {{ item }}"
  changed_when: false
  with_items:
    - "{{ global_filebeat_modules | default(None) }}"
    - "{{ filebeat_modules | default(None) }}"
  notify: Restart filebeat
  register: templates

- name: Listing current enabled filebeat modules
  shell: "ls *.yml"
  args:
    chdir: /etc/filebeat/modules.d/
  changed_when: false
  register: allTemplates

- name: Disable unmanaged filebeat modules
  command: "filebeat modules disable {{ item | replace('.yml', '') }}"
  with_items: "{{ allTemplates.stdout_lines }}"
  when: "item|replace('.yml', '') not in (templates.results|selectattr('item', 'string')|map(attribute='item')|list)"
