- block:
    - name: "Checking {{ target }}"
      shell: "{{ target }} version | awk '{ print $3 }'"
      changed_when: false
      register: verChk
      failed_when: verChk.stdout is version(elk_version, operator='lt', strict=True)
  rescue:
    - include_tasks: '{{ ansible_os_family }}.yml'
    - include_tasks: import_template.yml
      when: inventory_hostname == groups['all'][0]

- block:
    - name: Checking index default settings
      uri:
        url: "http://ingest.elastic.service.{{ consul_dc_name }}.consul:{{ elastic_http_port }}/_template/*"
  rescue:
    - import_role:
        name: deploy.ElasticSearch
        tasks_from: set_template.yml
  when: inventory_hostname == groups['all'][0]

- include_tasks: '{{ target }}_templates.yml'

- include_tasks: report.yml
