- block:
    - name: "Checking {{ target }}"
      shell: "{{ target }} version | awk '{ print $3 }'"
      changed_when: false
      register: verChk
      failed_when: verChk.stdout is version(elk_version, operator='lt', strict=True)
  rescue:
    - include_tasks: '{{ ansible_os_family }}.yml'
    - name: Importing elasticsearch template | http
      shell: "{{ target }} setup --template -E output.logstash.enabled=false -E output.redis.enabled=false -E output.elasticsearch.hosts='ingest.elastic.service.{{ consul_dc_name }}.consul:{{ elastic_http_port }}'"
      when:
        - inventory_hostname == groups['all'][-1]
        - not searchguard_enabled
    - name: Importing elasticsearch template | https
      shell: "{{ target }} setup --template -E output.logstash.enabled=false -E output.redis.enabled=false -E output.elasticsearch.hosts='https://ingest.elastic.service.{{ consul_dc_name }}.consul:{{ elastic_http_port }}' -E output.elasticsearch.username=kibanaserver -E output.elasticsearch.password={{ sg_users | selectattr('id', 'eq', 'kibanaserver') | map(attribute='pass') | first }} -E output.elasticsearch.ssl.verification_mode=none"
      when:
        - inventory_hostname == groups['all'][-1]
        - searchguard_enabled

- block:
    - name: Checking index default settings | http
      uri:
        url: "http://ingest.elastic.service.{{ consul_dc_name }}.consul:{{ elastic_http_port }}/_template/*"
  rescue:
    - import_role:
        name: deploy.ElasticSearch
        tasks_from: set_template.yml
  when:
    - inventory_hostname == groups['all'][-1]
    - not searchguard_enabled

- include_tasks: '{{ target }}_templates.yml'

- include_tasks: report.yml
