- block:
    - name: "Checking {{ target }}"
      shell: "{{ target }} version | awk '{ print $3 }'"
      changed_when: false
      register: verChk
      failed_when: verChk.stdout is version(elk_version, operator='lt', strict=True)
  rescue:
    - include_tasks: '{{ ansible_os_family }}.yml'
    - name: Importing elasticsearch template
      shell: "{{ target }} setup --template -E output.logstash.enabled=false -E output.redis.enabled=false -E output.elasticsearch.hosts='ingest.elastic.service.{{ consul_dc_name }}.consul:{{ elastic_http_port }}'"
      run_once: yes

- block:
    - name: Checking index default settings
      uri:
        url: http://ingest.elastic.service.{{ consul_dc_name }}.consul:{{ elastic_http_port }}/_template/active-logs
      run_once: yes
  rescue:
    - import_role:
        name: deploy.ElasticSearch
        tasks_from: set_template.yml
      run_once: yes

- include_tasks: '{{ target }}_templates.yml'
  tags: beats.config

- include_tasks: report.yml
