baseURL = "http://www.ansible-elk.cn"
languageCode = "zh"
title = "使用 Ansible 部署 ElasticSearch、Logstash、Kibana 和 Search Guard。"
theme = "theme-learn"

[params]
  author = "Haibin Lee"
  description = "Deploy ElasticSearch, Logstash, Kibana and 'Search Guard' in the Ansible way."
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"

[menu]
  [[menu.shortcuts]]
  name = "Git repo"
  url = "https://gitee.com/bottlelee/ansible-elk-deploy/"

  [[menu.shortcuts]]
  name = "Ansible Docs"
  url = "https://docs.ansible.com/ansible/latest/index.html"

  [[menu.shortcuts]]
  name = "Elastic Docs"
  url = "https://www.elastic.co/guide/index.html"

  [[menu.shortcuts]]
  name = "Consul Docs"
  url = "https://www.consul.io/docs/index.html"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
