baseURL = "http://bottlelee.gitee.io/ansible-elk-deploy/"
languageCode = "zh-cn"
title = "使用 Ansible 部署 ELK 和 Search Guard。"
theme = "kraiklyn"

[params]

[[menu.shortcuts]]
name = "源码下载"
url = "https://gitee.com/bottlelee/ansible-elk-deploy/tree/searchguard"
weight = 16
