- block:
    - name: 'Uploading logstash-{{ elk_version }}.deb'
      copy:
        src: 'downloaded_files/logstash-{{ elk_version }}.deb'
        dest: /tmp/
    - name: 'Installing logstash-{{ elk_version }}.deb'
      apt:
        deb: '/tmp/logstash-{{ elk_version }}.deb'
  rescue:
    - include_tasks: download.yml format=deb
    - include_tasks: '{{ ansible_os_family }}.yml'
  always:
    - name: 'Removing /tmp/logstash-{{ elk_version }}.deb'
      file:
        path: '/tmp/logstash-{{ elk_version }}.deb'
        state: absent
    # This task fix the logstash startup problem when it has no permission to write log in /var/log/logstash
    - name: Add user 'logstash' into group 'adm'
      user:
        name: logstash
        groups: adm
        append: yes
