- block:
    - name: 'uploading logstash-{{ elk_version }}.deb'
      copy:
        src: 'downloaded_files/logstash-{{ elk_version }}.deb'
        dest: /tmp/
    - name: 'installing logstash-{{ elk_version }}.deb'
      apt:
        deb: '/tmp/logstash-{{ elk_version }}.deb'
  rescue:
    - include_tasks: download.yml format=deb
    - include_tasks: '{{ ansible_os_family }}.yml'
  always:
    - name: 'removing /tmp/logstash-{{ elk_version }}.deb'
      file:
        path: '/tmp/logstash-{{ elk_version }}.deb'
        state: absent
