- block:
    - stat:
        path: "downloaded_files/logstash-{{ elk_version }}.{{ format }}"
      register: p
      failed_when: p.stat.exists == false
      delegate_to: localhost
      become: no
      run_once: true
  rescue:
    - name: 'Downloading logstash-{{ elk_version }}.{{ format }}'
      get_url:
        url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ elk_version }}.{{ format }}"
        dest: "downloaded_files/"
        validate_certs: no
      register: download
      until: download is succeeded
      retries: 5
      delay: 10
      delegate_to: localhost
      become: no
      run_once: yes
