- block:
    - name: checking logstash
      shell: /usr/share/logstash/bin/logstash -V | awk '{ print $2 }'
      changed_when: false
      register: verChk
      failed_when: verChk.stdout is version(elk_version, operator='lt', strict=True)
  rescue:
    - include_tasks: env_check.yml
      when: verChk.rc == 1
    - include_tasks: '{{ ansible_os_family }}.yml'

- name: updating logstash configuration
  template:
    src: '{{ item }}.j2'
    dest: '/etc/logstash/{{ item }}'
  with_items:
    - jvm.options
    - logstash.yml
  notify: restart logstash

- name: updating piplines
  template:
    src: '{{ item }}.conf.j2'
    dest: '/etc/logstash/conf.d/{{ item }}.conf'
  with_items:
    - 000-input
    - 001-logstash
    - 002-monit
    - 003-syslog
    - 004-auditd
    - 999-output
  notify: restart logstash

# - name: checking logstash configuration
#   command: /usr/share/logstash/bin/logstash -t --path.settings=/etc/logstash
#   notify: Restart logstash service
#   when: configSt is changed or pipelineSt is changed

- name: set /var/lib/logstash ownership
  file:
    path: '{{ item }}'
    state: directory
    owner: logstash
    group: logstash
    recurse: yes
  with_items:
    - '{{ logstash_log_path }}'
    - '{{ logstash_data_path }}'
