- block:
    - name: Checking logstash
      shell: /usr/share/logstash/bin/logstash -V | awk '{ print $2 }'
      changed_when: false
      register: verChk
      failed_when: verChk.stdout is version(elk_version, operator='lt', strict=True)
  rescue:
    - include_tasks: env_check.yml
      when: verChk.rc == 1
    - include_tasks: '{{ ansible_os_family }}.yml'
    - name: Updating logstash systemd service configure
      ini_file:
        path: /etc/systemd/system/logstash.service
        section: Service
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        backup: yes
      with_items:
        - option: PermissionsStartOnly
          value: true
        - option: ExecStartPre
          value: "/bin/chown -R logstash:logstash {{ logstash_data_path }} {{ logstash_log_path }}"
      notify: Restart logstash
    - name: Installing logrotate configure
      template:
        src: logrotate_logstash.j2
        dest: /etc/logrotate.d/logstash

- name: Updating logstash configuration
  template:
    src: '{{ item }}.j2'
    dest: '/etc/logstash/{{ item }}'
  with_items:
    - jvm.options
    - logstash.yml
  notify: Restart logstash

- name: Updating piplines
  template:
    src: '{{ item }}.conf.j2'
    dest: '/etc/logstash/conf.d/{{ item }}.conf'
  with_items:
    - 000-input
    - 001-logstash
    - 002-monit
    - 003-syslog
    - 004-auditd
    - 005-elasicsearch
    - 999-output
  notify: Checking logstash configuration
