- block:
    - name: Checking logstash
      shell: /usr/share/logstash/bin/logstash -V | awk '{ print $2 }'
      changed_when: false
      register: verChk
      failed_when: verChk.stdout is version(elk_version, operator='lt', strict=True)
  rescue:
    - include_tasks: env_check.yml
      when: verChk.rc == 1
    - include_tasks: '{{ ansible_os_family }}.yml'

- name: Updating logstash configuration
  template:
    src: '{{ item }}.j2'
    dest: '/etc/logstash/{{ item }}'
  with_items:
    - jvm.options
    - logstash.yml
  notify: Restart logstash

- name: Updating piplines
  template:
    src: '{{ item }}.conf.j2'
    dest: '/etc/logstash/conf.d/{{ item }}.conf'
  with_items:
    - 000-input
    - 001-logstash
    - 002-monit
    - 003-syslog
    - 004-auditd
    - 999-output
  notify: Restart logstash

- name: Set /var/lib/logstash ownership
  file:
    path: '{{ item }}'
    state: directory
    owner: logstash
    group: logstash
    mode: 0660
    recurse: yes
  with_items:
    - '{{ logstash_log_path }}'
    - '{{ logstash_data_path }}'
