- block:
    - name: 'Uploading logstash-{{ elk_version }}.rpm'
      copy:
        src: 'downloaded_files/logstash-{{ elk_version }}.rpm'
        dest: /tmp/
    - name: 'Installing logstash-{{ elk_version }}.rpm'
      yum:
        name: '/tmp/logstash-{{ elk_version }}.rpm'
  rescue:
    - include_tasks: download.yml format=rpm
    - include_tasks: '{{ ansible_os_family }}.yml'
  always:
    - name: 'Removing /tmp/logstash-{{ elk_version }}.rpm'
      file:
        path: '/tmp/logstash-{{ elk_version }}.rpm'
        state: absent
