- block:
    - name: 'Uploading logstash-{{ elk_version }}.rpm'
      copy:
        src: 'downloaded_files/elk-{{ elk_version }}/logstash-{{ elk_version }}.rpm'
        dest: /tmp/
    - name: 'Installing logstash-{{ elk_version }}.rpm'
      yum:
        name: '/tmp/logstash-{{ elk_version }}.rpm'
  rescue:
    - include_tasks: download.yml
      vars:
        format: rpm
    - include_tasks: '{{ ansible_os_family }}.yml'
    - meta: clear_host_errors
  always:
    - name: 'Removing /tmp/logstash-{{ elk_version }}.rpm'
      file:
        path: '/tmp/logstash-{{ elk_version }}.rpm'
        state: absent
