- block:
    - name: "Fetching /etc/logstash/logstash.yml to local 'install_report' directory"
      fetch:
        src: "/etc/logstash/logstash.yml"
        dest: "install_report"
        fail_on_missing: false
  rescue:
    - name: "Create local directory install_report/logstash"
      file:
        path: "install_report"
        state: directory
      delegate_to: localhost
      become: no
    - include_tasks: report.yml
