- block:
    - name: Checking python2
      raw: test -e /usr/bin/python
      changed_when: false
    - name: Create/update host_vars files
      lineinfile:
        path: "host_vars/{{ inventory_hostname }}.yml"
        regexp: "^ansible_python_interpreter"
        line: "ansible_python_interpreter: /usr/bin/python"
        create: yes
      delegate_to: localhost
      become: no
  rescue:
    - name: Checking python3
      raw: test -e /usr/bin/python3
      changed_when: false
    - name: Create/update host_vars files
      lineinfile:
        path: "host_vars/{{ inventory_hostname }}.yml"
        regexp: "^ansible_python_interpreter"
        line: "ansible_python_interpreter: /usr/bin/python3"
        create: yes
      delegate_to: localhost
      become: no
  when: (ansible_python_interpreter is not defined) or (ansible_python_interpreter == "/usr/bin/python")

- block:
    - name: Checking python3
      raw: test -e /usr/bin/python3
      changed_when: false
    - name: Create/update host_vars files
      lineinfile:
        path: "host_vars/{{ inventory_hostname }}.yml"
        regexp: "^ansible_python_interpreter"
        line: "ansible_python_interpreter: /usr/bin/python3"
        create: yes
      delegate_to: localhost
      become: no
  rescue:
    - name: Checking python
      raw: test -e /usr/bin/python
      changed_when: false
    - name: Create/update host_vars files
      lineinfile:
        path: "host_vars/{{ inventory_hostname }}.yml"
        regexp: "^ansible_python_interpreter"
        line: "ansible_python_interpreter: /usr/bin/python"
        create: yes
      delegate_to: localhost
      become: no
  when: (ansible_python_interpreter is not defined) or (ansible_python_interpreter == "/usr/bin/python3")

- block:
    - meta: clear_host_errors
    - meta: refresh_inventory
    - include_vars: "host_vars/{{ inventory_hostname }}.yml"
    - setup:
    - include_tasks: create_hostvars.yml
  rescue:
    - include_tasks: check_python.yml
