- block:
    - name: Extracting jre-8u161-linux-x64.tar.gz
      unarchive:
        src: downloaded_files/jre-8u161-linux-x64.tar.gz
        dest: /opt/
        owner: root
        group: root
    - name: Create soft link
      file:
        src: /opt/jre1.8.0_161/bin/java
        dest: /usr/bin/java
        owner: root
        group: root
        state: link
  rescue:
    - name: Downloading jre-8u161-linux-x64.tar.gz
      get_url:
        url: http://javadl.oracle.com/webapps/download/AutoDL?BundleId=230532_2f38c3b165be4555a1fa6e98c45e0808
        # headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
        dest: downloaded_files/jre-8u161-linux-x64.tar.gz
      register: download
      until: download is succeeded
      retries: 5
      delay: 10
      delegate_to: localhost
      become: no
      run_once: yes
    - include_tasks: jre.yml
