- name: Disable firewalld
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - firewalld
    - NetworkManager

- name: Disable selinux
  selinux:
    state: disabled

- name: "Setting /etc/sysconfig/network-scripts/ifcfg-{{ bind_interface }}"
  lineinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ bind_interface }}"
    line: "{{ item }}"
  with_items:
    - "DNS1={{ dns_servers[0] }}"
    - "DNS2={{ dns_servers[1] }}"
    - "PEERDNS=yes"
  notify: Restart network service
