- name: Disable firewalld and selinux
  block:
    - service:
        name: firewalld
        state: stopped
        enabled: no
    - selinux:
        state: disabled
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version >= '7'"

- name: Disable NetworkManager service
  service:
    name: NetworkManager
    state: stopped
    enabled: no

- name: Setup dns server
  lineinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ bind_interface }}"
    line: "{{ item }}"
  with_items:
    - "DNS1={{ dns_servers[0] }}"
    - "DNS2={{ dns_servers[1] }}"
  register: resolvconf

- name: Enable network service
  service:
    name: network
    state: restarted
    enabled: yes
  when: resolvconf is changed
