- name: "Checking {{ bind_interface }}"
  fail:
    msg: "interface {{ bind_interface }} has no IP address"
  when: hostvars[inventory_hostname]['ansible_' + bind_interface]['ipv4']['address'] == ''

- name: Setup sysctl
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    ignoreerrors: yes
  with_items: "{{ sysctl_rules | sort }}"

- name: Disable swap
  command: swapoff -a
  when: "'elasticsearch' in group_names"
  changed_when: false

- name: "Setup timezone to {{ timezone }}"
  timezone:
    name: '{{ timezone }}'
