- name: "Checking {{ bind_interface }}"
  fail:
    msg: "interface {{ bind_interface }} has no IP address"
  when: hostvars[inventory_hostname]['ansible_' + bind_interface]['ipv4']['address'] == ''

- name: Setup sysctl
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: '{{ item.state | default("present") }}'
    ignoreerrors: yes
  with_items: "{{ sysctl_rules | sort }}"

- name: Disable swap
  command: swapoff -a
  changed_when: false
  when:
    - ansible_swaptotal_mb > 0
    - "'elasticsearch' in group_names"

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: "Setup timezone to {{ timezone }}"
  timezone:
    name: '{{ timezone }}'
