- block:
    - name: Checking kibana version
      command: "/usr/share/kibana/bin/kibana version"
      changed_when: false
      register: verChk
      failed_when: verChk.stdout is version(elk_version, operator='lt', strict=True)
    - name: Checking kibana service status
      wait_for:
        host: "{{ bind_address }}"
        port: '{{ kibana_port }}'
        timeout: 10
  rescue:
    - include_tasks: '{{ ansible_os_family }}.yml'
    - name: Create /var/log/kibana
      file:
        path: /var/log/kibana
        state: directory
        owner: kibana
        group: kibana
    - name: Starting kibana service
      service:
        name: kibana
        state: restarted
        enabled: yes
        daemon_reload: yes

- name: Update kibana configuration
  template:
    src: 'kibana/{{ item }}.j2'
    dest: '/etc/kibana/{{ item }}'
  with_items:
    - kibana.yml
  notify: Restart kibana

- include_tasks: searchguard/main.yml
  when: searchguard_enabled

- include_tasks: report.yml
