- block:
    - name: 'Uploading kibana-{{ elk_version }}-x86_64.rpm'
      copy:
        src: 'downloaded_files/kibana-{{ elk_version }}-x86_64.rpm'
        dest: /tmp/
    - name: 'Installing kibana-{{ elk_version }}-x86_64.rpm'
      yum:
        name: '/tmp/kibana-{{ elk_version }}-x86_64.rpm'
        state: present
  rescue:
    - include_tasks: download.yml format=rpm
    - include_tasks: '{{ ansible_os_family }}.yml'
    - meta: clear_host_errors
  always:
    - name: 'Removing /tmp/kibana-{{ elk_version }}-x86_64.rpm'
      file:
        path: '/tmp/kibana-{{ elk_version }}-x86_64.rpm'
        state: absent
