- block:
    - name: Uploading packages
      copy:
        src: "downloaded_files/{{ item | basename }}"
        dest: "/tmp/{{ item | basename }}"
      with_items: "{{ deb_haproxy_urls }}"
    - name: Installing packages
      apt:
        deb: "/tmp/{{ item | basename }}"
      with_items: "{{ deb_haproxy_urls }}"
  rescue:
    - include_tasks: download.yml format='deb'
    - include_tasks: Debian.yml
