- name: Downloading deb packages
  get_url:
    url: "{{ item }}"
    dest: "downloaded_files/{{ item | basename }}"
  with_items: "{{ deb_haproxy_urls }}"
  delegate_to: localhost
  become: no
  run_once: yes
  register: download
  until: download is succeeded
  retries: 99
  delay: 3
  when: "format == 'deb'"

- name: Downloading rpm packages
  get_url:
    url: "{{ item }}"
    dest: "downloaded_files/{{ item | basename }}"
  with_items: "{{ rpm_haproxy_urls }}"
  delegate_to: localhost
  become: no
  run_once: yes
  register: download
  until: download is succeeded
  retries: 99
  delay: 3
  when: "format == 'rpm'"
